export const SET_D2 = 'SET_D2';
export const SET_DATABASE = 'SET_DATABASE';
export const LOADING = 'LOADING';

export const GRID_STATE_CHANGE_ACTION = 'GRID_STATE_CHANGE';
export const GRID_ADD_METADATA = 'GRID_ADD_METADATA';
export const GRID_ADD_DEPENDENCIES = 'GRID_ADD_DEPENDENCIES';