export const SET_D2 = 'SET_D2';
export const LOADING = 'LOADING';

export const GRID_STATE_CHANGE = 'GRID_STATE_CHANGE';
export const GRID_ADD_METADATA = 'GRID_ADD_METADATA';
export const GRID_ADD_DEPENDENCIES = 'GRID_ADD_DEPENDENCIES';
export const GRID_REMOVE_FROM_SELECTION = 'GRID_REMOVE_FROM_SELECTION';

export const DIALOG_ADMIN_SHOW = 'DIALOG_ADMIN_SHOW';
export const DIALOG_OPTIONS_SHOW = 'DIALOG_OPTIONS_SHOW';
export const DIALOG_JSON_UPDATE = 'DIALOG_JSON_UPDATE';
export const DIALOG_JSON_SHOW = 'DIALOG_JSON_SHOW';
export const SNACKBAR_UPDATE = 'SNACKBAR_UPDATE';
export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';

export const GET_USER_BLACKLIST = 'GET_USER_BLACKLIST';
export const UPDATE_USER_BLACKLIST = 'UPDATE_USER_BLACKLIST';

export const SETTINGS_ORG_UNIT_CHILDREN = 'SETTINGS_ORG_UNIT_CHILDREN';
export const SETTINGS_USER_CLEAN_UP = 'SETTINGS_USER_CLEAN_UP';